name: multicraft # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.0.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Ubuntu version of the voxel game Multicraft
description: |
  This is the Ubuntu version of the voxel game Multicraft, very much like Minecraft

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  MultiCraft_Icon1.png
title: Multicraft

apps:
  multicraft:
    command: bin/multicraft
parts:
  multicraft:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      multicraft: build/
      multicraft.1: man/man1/

architectures:
  - build-on: amd64

